### ISSUE TITLE
runs then dies

### ISSUE THREAD

**Issue by karstenxavier** [nanometer5088/CLI-TikTok#1]
when i run the main.py  it runs then closes , any suggestions?

**Comment by ovosimpatico** [comment]
That is not supposed to happen. 

Can you post any video of that happening, or any error that might appear? Without further information, I'm not able to be useful.

What Python version are you running, and what operating system are you running? Are you running this software inside an IDE, or on a terminal?

**Comment by ovosimpatico** [comment]
Also try downloading [the latest release](https://github.com/nanometer5088/CLI-TikTok/releases) and try again.

**Comment by ovosimpatico** [comment]
I'm closing this issue because I can't reproduce your issue, and because of the lack of activity and information.

You can reopen this issue if the situation persists.
