### ISSUE TITLE
Can't download liked videos

### ISSUE THREAD

**Issue by pikpoket** [nanometer5088/CLI-TikTok#4]
Hi, thank you for your work,
I can't figure out why the script says that the option I choosed isn't valid. I selected the correct options multiple time (pressing 1 on my keyboard).

**Describe the bug**
Can't download liked videos

**To Reproduce**
Press 1 twice after running main.py

Log file:
[log-8.txt](https://github.com/ovosimpatico/CLI-TikTok/files/14166277/log-8.txt)

**Comment by ovosimpatico** [comment]
I can reproduce this issue, and will try to issue a fix.

I haven't worked on this project for a while, so I can't guarantee it's still working though.

**Comment by ovosimpatico** [comment]
The issue was related to character encoding. It should be fixed now. Thanks for reporting this issue :)

**Comment by pikpoket** [comment]
You rocks thanks
